export const NAMES = {
    AZUCAR: 'Azucar',
    COCINAR: 'Cocinar',
    HARINA: 'Harina',
    VENDER: 'Vender',
    DINERO: 'Dinero',
    SAL: 'Sal',
    REALIZARMASA: 'RealizarMasa',
    MASAMADRE: 'MasaMadre',
    SEPARARMASA: 'SepararMasa',
    PAN: 'Pan',
    ACEITE: 'Aceite',
    MASA: 'Masa',
    LEVADURA: 'Levadura',
}
