export const TYPES = {
	HARINA: 'Harina',
	SEPARARMASA: 'SepararMasa',
	PANADERO: 'Panadero',
	COCINAR: 'Cocinar',
	PAN: 'Pan',
	VENDER: 'Vender',
	DINERO: 'Dinero',
	ACEITE: 'Aceite',
	MASA: 'Masa',
	LEVADURA: 'Levadura',
	AZUCAR: 'Azucar',
	SAL: 'Sal',
	REALIZARMASA: 'RealizarMasa',
	PROVEEDOR: 'Proveedor',
	MASAMADRE: 'MasaMadre',
}
