export const TYPES = {
	MECANICO: 'Mecanico',
	METAL: 'Metal',
	COCHE: 'Coche',
	MONTARRUEDAS: 'MontarRuedas',
	MONTARCARROCERIA: 'MontarCarroceria',
	RUEDA: 'Rueda',
	MONTARBASE: 'MontarBase',
	MONTARMOTOR: 'MontarMotor',
	VOLANTE: 'Volante',
	COCHEFASE1: 'CocheFase1',
	BASE: 'Base',
	MONTARESQUELETO: 'MontarEsqueleto',
	ADMINISTRADOR: 'Administrador',
	ESQUELETO: 'Esqueleto',
	VENDER: 'Vender',
	MAQUINA: 'Maquina',
	PINTAR: 'Pintar',
	PINTOR: 'Pintor',
	OPERARIO: 'Operario',
	MOTOR: 'Motor',
	COCHEFASE2: 'CocheFase2',
	PLASTICO: 'Plastico',
	MONTARVOLANTE: 'MontarVolante',
	VENDEDOR: 'Vendedor',
	COCHEFASE3: 'CocheFase3',
	CARROCERIA: 'Carroceria',
}
