export const NAMES = {
    CLEAN_OIL: 'Clean oil',
    GRIDING: 'Griding',
    REPORT: 'Report',
    COLLECT: 'Collect',
    OLIVE_PASTE_PHASE_2: 'Olive paste phase 2',
    HORIZONTAL_CENTRIFUGIN: 'Horizontal Centrifugin',
    MIXING: 'Mixing',
    LABELLING: 'Labelling',
    DIRTY_OIL_PHASE_2: 'Dirty oil phase 2',
    OIL_BOTTLE_PHASE_1: 'Oil bottle phase 1',
    PACKAGING: 'Packaging',
    OLIVE_PASTE_PHASE_1: 'Olive paste phase 1',
    OLIVE_BATCH_PHASE_1: 'Olive batch phase 1',
    WEIGHING: 'Weighing',
    DIRTY_OIL_PHASE_1: 'Dirty oil phase 1',
    OIL_BOTTLE_PHASE_2: 'Oil bottle phase 2',
    VERTICAL_CENTRIFUGING: 'Vertical Centrifuging',
    DECANTING: 'Decanting',
    OLIVE_BATCH_PHASE_2: 'Olive batch phase 2',
    SAMPLING: 'Sampling',
    OLIVE_BATCH_PHASE_3: 'Olive batch phase 3',
}
