<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="TraceabilityMM" nsURI="http://www.example.org/TraceabilityMM"
    nsPrefix="TraceabilityMM">
  <eAnnotations source="gmf"/>
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Node" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transaction" eSuperTypes="#//Node">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="label.placement" value="external"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/TFG-TrustOS_Traceability/icons/SVG/transaction.svg"/>
      <details key="tool.name" value="Transaction"/>
      <details key="tool.description" value="Create a transaction"/>
    </eAnnotations>
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="Description"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transactionconf" lowerBound="1"
        eType="#//TransactionConf" eOpposite="#//TransactionConf/transaction">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
        <details key="color" value="0,38,175"/>
        <details key="tool.name" value="Transaction configuration"/>
        <details key="tool.description" value="Link a transaction to it configuration"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next_product" lowerBound="1"
        upperBound="-1" eType="#//Product" eOpposite="#//Product/previous_transaction">
      <eAnnotations source="gmf.link">
        <details key="source" value="previous_transaction"/>
        <details key="target" value="next_product"/>
        <details key="target.decoration" value="filledclosedarrow"/>
        <details key="style" value="solid"/>
        <details key="color" value="0,0,0"/>
        <details key="tool.name" value="Next product"/>
        <details key="tool.description" value="Link the transaction to next product"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previous_product" upperBound="-1"
        eType="#//Product" eOpposite="#//Product/next_transaction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product" eSuperTypes="#//Node">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="svg"/>
      <details key="label.placement" value="external"/>
      <details key="svg.uri" value="platform:/plugin/TFG-TrustOS_Traceability/icons/SVG/product.svg"/>
      <details key="tool.name" value="Product"/>
      <details key="tool.description" value="Create a product"/>
    </eAnnotations>
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="Description"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="productconf" lowerBound="1"
        eType="#//ProductConf" eOpposite="#//ProductConf/product">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
        <details key="color" value="0,174,102"/>
        <details key="tool.name" value="Product configuration"/>
        <details key="tool.description" value="Link a product to it configuration"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previous_transaction" upperBound="-1"
        eType="#//Transaction" eOpposite="#//Transaction/next_product"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next_transaction" upperBound="-1"
        eType="#//Transaction" eOpposite="#//Transaction/previous_product">
      <eAnnotations source="gmf.link">
        <details key="source" value="previous_product"/>
        <details key="target" value="next_transaction"/>
        <details key="target.decoration" value="filledclosedarrow"/>
        <details key="style" value="solid"/>
        <details key="color" value="0,0,0"/>
        <details key="tool.name" value="Next transaction"/>
        <details key="tool.description" value="Link the product to next transaction"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransactionConf" eSuperTypes="#//Asset">
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="MomentInterval"/>
    </eAnnotations>
    <eAnnotations source="gmf.node">
      <details key="label" value="type"/>
      <details key="label.placement" value="external"/>
      <details key="border.width" value="0"/>
      <details key="border.color" value="0,38,175"/>
      <details key="border.style" value="solid"/>
      <details key="svg.uri" value="platform:/plugin/TFG-TrustOS_Traceability/icons/SVG/transactionConf.svg"/>
      <details key="tool.name" value="Transaction Configuration"/>
      <details key="tool.description" value="Create a configuration for transaction"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repeat" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transaction" lowerBound="1"
        upperBound="-1" eType="#//Transaction" eOpposite="#//Transaction/transactionconf"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isTransactionInfinite"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        volatile="true" transient="true" defaultValueLiteral="false" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="self.repeat = -1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isTransactionFinal" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" volatile="true"
        transient="true" defaultValueLiteral="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="self.final"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductConf" eSuperTypes="#//Asset">
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="Description"/>
    </eAnnotations>
    <eAnnotations source="gmf.node">
      <details key="label" value="type"/>
      <details key="label.placement" value="external"/>
      <details key="border.width" value="0"/>
      <details key="border.color" value="0,174,102"/>
      <details key="border.style" value="solid"/>
      <details key="svg.uri" value="platform:/plugin/TFG-TrustOS_Traceability/icons/SVG/productConf.svg"/>
      <details key="tool.name" value="Product Configuration"/>
      <details key="tool.description" value="Create a configuration for product"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="transactionsFinals"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="transactionsFinals" value="self.product.next_transaction.transactionconf->select(isTransactionInfinite)->size() >= 1 implies self.product.next_transaction.transactionconf->select(isTransactionFinal)->size() >= 1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="product" lowerBound="1"
        upperBound="-1" eType="#//Product" eOpposite="#//Product/productconf"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RolConf" eSuperTypes="#//Asset">
    <eAnnotations source="gmf.node">
      <details key="label" value="type"/>
      <details key="label.placement" value="external"/>
      <details key="border.width" value="0"/>
      <details key="border.color" value="220,31,31"/>
      <details key="border.style" value="solid"/>
      <details key="svg.uri" value="platform:/plugin/TFG-TrustOS_Traceability/icons/SVG/rolConf.svg"/>
      <details key="tool.name" value="Rol Configuration"/>
      <details key="tool.description" value="Create a configuration for rol"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="onePermissionTotal noMoreOneEdit noMoreOneView noMoreOneCreate"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="onePermissionTotal" value="self.permissions->selectByType(Permission)->size() &lt;= 1"/>
      <details key="noMoreOneEdit" value="self.permissions->selectByType(Edit)->size() &lt;= 1"/>
      <details key="noMoreOneView" value="self.permissions->selectByType(View)->size() &lt;= 1"/>
      <details key="noMoreOneCreate" value="self.permissions->selectByType(Create)->size() &lt;= 1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="permissions" lowerBound="1"
        upperBound="-1" eType="#//Permission">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
        <details key="color" value="220,31,31"/>
        <details key="tool.name" value="Permission of a rol"/>
        <details key="tool.description" value="Link the rol to it permissions"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Asset" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" lowerBound="1"
        upperBound="-1" eType="#//Property" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="collapsible" value="true"/>
        <details key="layout" value="list"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Permission">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="label.placement" value="external"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/TFG-TrustOS_Traceability/icons/SVG/permission.svg"/>
      <details key="tool.name" value="Permission to do all"/>
      <details key="tool.description" value="Create a permission to do all for a rol"/>
    </eAnnotations>
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="MomentInterval"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refers" lowerBound="1"
        upperBound="-1" eType="#//Property" eOpposite="#//Property/allow">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
        <details key="color" value="192,192,192"/>
        <details key="tool.name" value="Properties allow"/>
        <details key="tool.description" value="Link the properties that the permission allow"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Edit" eSuperTypes="#//Permission">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="label.placement" value="external"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/TFG-TrustOS_Traceability/icons/SVG/edit.svg"/>
      <details key="tool.name" value="Permission to edit"/>
      <details key="tool.description" value="Create a permission to edit for a rol"/>
    </eAnnotations>
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="MomentInterval"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Create" eSuperTypes="#//Permission">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="label.placement" value="external"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/TFG-TrustOS_Traceability/icons/SVG/create.svg"/>
      <details key="tool.name" value="Permission to create"/>
      <details key="tool.description" value="Create a permission to create for a rol"/>
    </eAnnotations>
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="MomentInterval"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="View" eSuperTypes="#//Permission">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="label.placement" value="external"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/TFG-TrustOS_Traceability/icons/SVG/view.svg"/>
      <details key="tool.name" value="Permission to view"/>
      <details key="tool.description" value="Create a permission to view for a rol"/>
    </eAnnotations>
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="MomentInterval"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="System">
    <eAnnotations source="emf.gen">
      <details key="fileExtensions" value="trustd"/>
    </eAnnotations>
    <eAnnotations source="gmf.diagram">
      <details key="label" value="name"/>
      <details key="diagram.extension" value="trust"/>
      <details key="model.extension" value="trustd"/>
    </eAnnotations>
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="Role"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assets" upperBound="-1"
        eType="#//Asset" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="permissions" upperBound="-1"
        eType="#//Permission" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="propertiesAllow"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="propertiesAllow" value=" (self.oclContainer().oclIsTypeOf(ProductConf) or self.oclContainer().oclIsTypeOf(TransactionConf)) implies self.allow->size() > 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allow" upperBound="-1"
        eType="#//Permission" eOpposite="#//Permission/refers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//Property">
    <eAnnotations source="gmf.node">
      <details key="label" value="id"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/TFG-TrustOS_Traceability/icons/SVG/attribute.svg"/>
      <details key="tool.name" value="Attribute"/>
      <details key="tool.description" value="Create a attribute in a configuration"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//Value" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="collapsible" value="true"/>
        <details key="layout" value="list"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//EType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object" eSuperTypes="#//Property">
    <eAnnotations source="gmf.node">
      <details key="label" value="id"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/TFG-TrustOS_Traceability/icons/SVG/object.svg"/>
      <details key="tool.name" value="Object"/>
      <details key="tool.description" value="Create a object of attributes in a configuration"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" lowerBound="2"
        upperBound="-1" eType="#//Property" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="collapsible" value="true"/>
        <details key="layout" value="list"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/TFG-TrustOS_Traceability/icons/SVG/value.svg"/>
      <details key="tool.name" value="Value of attribute"/>
      <details key="tool.description" value="Create a value of one attribute"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EType">
    <eLiterals name="String"/>
    <eLiterals name="Number" value="1"/>
    <eLiterals name="Decimal" value="2"/>
    <eLiterals name="Boolean" value="3"/>
    <eLiterals name="Date" value="4"/>
    <eLiterals name="Email" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TemporalTransaction" eSuperTypes="#//Transaction">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/TFG-TrustOS_Traceability/icons/SVG/temporalTransaction.svg"/>
      <details key="tool.name" value="Temporal transaction"/>
      <details key="tool.description" value="Create a temporal transaction"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
