<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="TraceabilityMM" nsURI="http://www.example.org/TraceabilityMM"
    nsPrefix="TraceabilityMM">
  <eAnnotations source="gmf"/>
  <eClassifiers xsi:type="ecore:EClass" name="Rol" eSuperTypes="#//Asset">
    <eAnnotations source="gmf.node">
      <details key="label" value="assetID"/>
      <details key="border.width" value="0"/>
      <details key="border.color" value="220,31,31"/>
      <details key="border.style" value="solid"/>
    </eAnnotations>
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="MomentInterval"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="permissions" lowerBound="1"
        upperBound="-1" eType="#//Permission">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
        <details key="color" value="220,31,31"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="access" lowerBound="1"
        upperBound="-1" eType="#//Node">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
        <details key="color" value="220,31,31"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransactionConf" eSuperTypes="#//Asset">
    <eAnnotations source="gmf.node">
      <details key="label" value="assetID"/>
      <details key="border.width" value="0"/>
      <details key="border.color" value="0,38,174"/>
      <details key="border.style" value="solid"/>
    </eAnnotations>
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="Description"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="System">
    <eAnnotations source="emf.gen">
      <details key="fileExtensions" value="trustd"/>
    </eAnnotations>
    <eAnnotations source="gmf.diagram">
      <details key="label" value="name"/>
      <details key="diagram.extension" value="trust"/>
      <details key="model.extension" value="trustd"/>
    </eAnnotations>
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="Role"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assets" upperBound="-1"
        eType="#//Asset" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//Rol" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="permissions" upperBound="-1"
        eType="#//Permission" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Permission">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/TFG-TrustOS-Traceability/icons/SVG/permission.svg"/>
    </eAnnotations>
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="MomentInterval"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" lowerBound="1"
        upperBound="-1" eType="#//Property">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
        <details key="color" value="141,28,167"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="where" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="View" eSuperTypes="#//Permission">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/TFG-TrustOS-Traceability/icons/SVG/view.svg"/>
    </eAnnotations>
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="MomentInterval"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="view_all" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Create" eSuperTypes="#//Permission">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/TFG-TrustOS-Traceability/icons/SVG/create.svg"/>
    </eAnnotations>
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="MomentInterval"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Edit" eSuperTypes="#//Permission">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/TFG-TrustOS-Traceability/icons/SVG/edit.svg"/>
    </eAnnotations>
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="MomentInterval"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="edit_all" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductConf" eSuperTypes="#//Asset">
    <eAnnotations source="gmf.node">
      <details key="label" value="assetID"/>
      <details key="border.width" value="0"/>
      <details key="border.color" value="0,174,101"/>
      <details key="border.style" value="solid"/>
    </eAnnotations>
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="Thing"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transaction" eSuperTypes="#//Node">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/TFG-TrustOS-Traceability/icons/SVG/transaction.svg"/>
    </eAnnotations>
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="Description"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transactionconf" lowerBound="1"
        eType="#//TransactionConf">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
        <details key="color" value="0,38,174"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previous" upperBound="-1"
        eType="#//Product" eOpposite="#//Product/next"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" lowerBound="1" upperBound="-1"
        eType="#//Product" eOpposite="#//Product/previous">
      <eAnnotations source="gmf.link">
        <details key="source" value="previous"/>
        <details key="source.decoration" value="closedarrow"/>
        <details key="target" value="next"/>
        <details key="target.decoration" value="filledclosedarrow"/>
        <details key="style" value="solid"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subtransaction" upperBound="-1"
        eType="#//Transaction">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
        <details key="color" value="0,38,174"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product" eSuperTypes="#//Node">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/TFG-TrustOS-Traceability/icons/SVG/product.svg"/>
    </eAnnotations>
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="Thing"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="productconf" lowerBound="1"
        eType="#//ProductConf">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
        <details key="color" value="0,174,101"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" upperBound="-1" eType="#//Transaction"
        eOpposite="#//Transaction/previous">
      <eAnnotations source="gmf.link">
        <details key="source" value="previous"/>
        <details key="source.decoration" value="closedarrow"/>
        <details key="target" value="next"/>
        <details key="target.decoration" value="filledclosedarrow"/>
        <details key="style" value="solid"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previous" upperBound="-1"
        eType="#//Transaction" eOpposite="#//Transaction/next"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EType">
    <eLiterals name="String"/>
    <eLiterals name="Number" value="1"/>
    <eLiterals name="Boolean" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//Property">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="svg"/>
      <details key="svg.uri" value="platform:/plugin/TFG-TrustOS-Traceability/icons/SVG/attribute.svg"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//EType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//Value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object" eSuperTypes="#//Property">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="border.width" value="0"/>
      <details key="border.color" value="236,239,66"/>
      <details key="border.style" value="solid"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" lowerBound="2"
        upperBound="-1" eType="#//Property" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="collapsible" value="true"/>
        <details key="layout" value="free"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Asset" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assetID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="collapsible" value="true"/>
        <details key="layout" value="free"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mutable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value"/>
</ecore:EPackage>
